// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0zp-Cw-W-O0kCN8PRZkeLW9ERjPsMB8',
    appId: '1:263975888157:web:d08c0ff9f819f0831fedf4',
    messagingSenderId: '263975888157',
    projectId: 'addis-ecommerce-a0d4f',
    authDomain: 'addis-ecommerce-a0d4f.firebaseapp.com',
    storageBucket: 'addis-ecommerce-a0d4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIlBZTr4Wntu5c6tTbRJh7SoFy3_OfSo',
    appId: '1:263975888157:android:2ab672ad3cb0768a1fedf4',
    messagingSenderId: '263975888157',
    projectId: 'addis-ecommerce-a0d4f',
    storageBucket: 'addis-ecommerce-a0d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ytjjqZ23J-3npU0-Z0WHfatax1ftLoE',
    appId: '1:263975888157:ios:fcf05edb3a7e34cf1fedf4',
    messagingSenderId: '263975888157',
    projectId: 'addis-ecommerce-a0d4f',
    storageBucket: 'addis-ecommerce-a0d4f.firebasestorage.app',
    iosBundleId: 'com.addiscodr.addisEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ytjjqZ23J-3npU0-Z0WHfatax1ftLoE',
    appId: '1:263975888157:ios:fcf05edb3a7e34cf1fedf4',
    messagingSenderId: '263975888157',
    projectId: 'addis-ecommerce-a0d4f',
    storageBucket: 'addis-ecommerce-a0d4f.firebasestorage.app',
    iosBundleId: 'com.addiscodr.addisEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0zp-Cw-W-O0kCN8PRZkeLW9ERjPsMB8',
    appId: '1:263975888157:web:faab01b97e2cd5451fedf4',
    messagingSenderId: '263975888157',
    projectId: 'addis-ecommerce-a0d4f',
    authDomain: 'addis-ecommerce-a0d4f.firebaseapp.com',
    storageBucket: 'addis-ecommerce-a0d4f.firebasestorage.app',
  );
}
